MinGW: 'http://127.0.0.1/WMS/mirrors/MinGW.zip'

mirror:
  http:
    server:
       http://127.0.0.1/WMS/mirrors:
          - gstreamer.freedesktop.org
          - ftp.gnome.org
          - ftp.gnu.org
          - www.opengl.org
          - www.openssl.org
          - www.tortall.net
          - github.com
  git:
    'git://anongit.freedesktop.org/gstreamer-sdk/windows-external-sdk.git' : 'https://github.com/freedesktop/gstreamer-sdk-windows-external-sdk.git'

    

