#!/usr/bin/env python
import sys
import os

__dir__=os.path.abspath( os.path.dirname(__file__) )
sys.path.insert(0, os.path.join(__dir__,'scripts/cerbero'))
import cerberus

make = cerberus.MakeProject()
make.run()

